
services:
  rasa:
    image: rasa/rasa:3.6.0-full
    container_name: rasa
    volumes:
      - ./models:/app/models       # mount models
    ports:
      - "5005:5005"
    command: >
      run
      --model /app/models
      --enable-api
      --cors "*"
      --debug

  backend:
    build: .
    container_name: backend
    volumes:
      - ./:/app
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - rasa
